name: Build VST3 Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Steinberg VST3 SDK
      run: git clone --depth 1 https://github.com/steinbergmedia/vst3sdk.git vst3sdk

    - name: Configure build with CMake
      run: cmake -S . -B build -DVST3_SDK_DIR=./vst3sdk -A x64

    - name: Build plugin
      run: cmake --build build --config Release

    - name: Upload VST3 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Plugin-VST3
        path: |
          build/**/*.vst3
          build/**/*.dll
